name: lint
on:
  push:
  pull_request:

jobs:
  build-tools:
    runs-on: ubuntu-latest
    name: prepare
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-

  lint:
    name: lint
    needs: build-tools
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-
      - name: go-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.51.1'
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true